setup:
    addons:
        - plan: timber-logging:free
          as: LOGGING
        - plan: cloudamqp:lemur
          as: QUEUE
        - plan:
    config:
        NODE_ENV: production
        NODE_PATH: src
        ENVIRONMENT: heroku
    build:
        docker:
            web: build/heroku/web/Dockerfile
    release:
        command:
            - ./deployment-tasks.sh
        image: worker
    run:
        web: yarn start --only api
